# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock.xci
# IP: The module: 'fast_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock.xci
# IP: The module: 'fast_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fast_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
