# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs.xci
# IP: The module: 'FTDI_FIFOs' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs.xdc
# XDC: The top module name and the constraint reference have the same name: 'FTDI_FIFOs'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FTDI_FIFOs'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FTDI_FIFOs'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs.xci
# IP: The module: 'FTDI_FIFOs' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs.xdc
# XDC: The top module name and the constraint reference have the same name: 'FTDI_FIFOs'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FTDI_FIFOs'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FTDI_FIFOs'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
