# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator.xci
# IP: The module: 'DTClockGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator.xci
# IP: The module: 'DTClockGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DTClockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
