# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7k160tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.cache/wt [current_project]
set_property parent.project_path /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/ADC1.v
read_vhdl -library xil_defaultlib {
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/ADC_FRAME_S.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/CitirocAnalogReadoutV2.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/CitirocFrameTransferV2.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/CitirocSlowControl.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/DT5550W_iic.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/FlashController.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/MCRateMeter.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/PULSE_GENERATOR.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/TimestampGenerator.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/U447_custompacket.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/adc_interface.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/adc_sync.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/adcs_top.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/chronoenable.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/comparator.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/counter_rising.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/d_latch.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/edge_pos.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/ff_sr.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/flash_prog.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/frequency_meter.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/ft600_fifo245_core.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/ft600_fifo245_wrapper.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/init_clock_gen.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/pulseshaper.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/security.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/spi32bit_master_write.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/spi93lc56_16bit.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/spi_timing_module.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/subpage_Framing.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/subpage_Timer64.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/subpage_TriggerLogic.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/subpage_frameproc.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/tdc_sync_nofifo.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/xlx_oscilloscope_sync.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/pcores/xlx_soft_gd.vhd
  /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/imports/HDL/top_CitirocRedoutFullV.vhd
}
read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/TestBram/TestBram.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/TestBram/TestBram_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_board.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_late.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/DTClockGenerator/DTClockGenerator_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll_board.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFO_AW/FTDI_FIFO_AW.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFO_AW/FTDI_FIFO_AW.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFO_AW/FTDI_FIFO_AW_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFO_AW/FTDI_FIFO_AW_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FTDI_FIFOs/FTDI_FIFOs_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FlashPageMemory/FlashPageMemory.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/FlashPageMemory/FlashPageMemory_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock.xci
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_board.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_late.xdc]
set_property used_in_implementation false [get_files -all /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/fast_clock/fast_clock_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/constrs_1/imports/HDL/dt555w_constraints.xdc
set_property used_in_implementation false [get_files /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/constrs_1/imports/HDL/dt555w_constraints.xdc]


synth_design -top TOP_CitirocRedoutFullV -part xc7k160tffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_CitirocRedoutFullV.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_CitirocRedoutFullV_utilization_synth.rpt -pb TOP_CitirocRedoutFullV_utilization_synth.pb"
