# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll.xci
# IP: The module: 'tdc_05ns_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdc_05ns_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdc_05ns_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdc_05ns_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll.xci
# IP: The module: 'tdc_05ns_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdc_05ns_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdc_05ns_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/utente/projects/CitirocRedoutFullV/CitirocRedoutFullV.srcs/sources_1/ip/tdc_05ns_pll/tdc_05ns_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdc_05ns_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
